import { LoginPage } from '../../support/pages/login.page'

it('shows a login error refactored', () => {
  cy.visit('/')
  LoginPage.getUsername().type('locked_out_user')
  LoginPage.getPassword().type('secret_sauce')
  LoginPage.noErrors()
  LoginPage.getLogin().click()
  cy.log('**shows errors**')
  LoginPage.getUsername().should('have.class', 'error')
  LoginPage.getPassword().should('have.class', 'error')
  cy.location('pathname').should('equal', '/')
  LoginPage.getError()
    .should('include.text', 'locked out')
    .and('be.visible')
    .wait(1000)
    .find('button.error-button')
    .click()
  LoginPage.noErrors()
  LoginPage.getUsername().should('have.value', 'locked_out_user')
  LoginPage.getPassword().should('have.value', 'secret_sauce')
})
