name: Cypress CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0  # Ensure it matches your local environment version

      - name: Install dependencies
        run: npm ci  # Ensure all dependencies, including start-server-and-test, are installed

      - name: Run CI
        run: npm run ci  # Start the server, wait for it to be ready, and run Cypress tests

      - name: Upload Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome-report/
          retention-days: 5
